### PR TITLE
Updated Papers

### PR DESCRIPTION
**Pull request by lorenarm96**

### CODE REVIEW

**Comment by lorenarm96** [comment]
@jaimergp

**Comment by jaimergp** [comment]
The images are missing @lorenarm96. They are expected at:

* images/publications/roldan2021.png
* images/publications/sanchez2021.png

Screenshot 2021-06-11 at 13 49 31

**Comment by lorenarm96** [comment]
Let's see now @jaimergp

**Comment by jaimergp** [comment]
LGTM!

**Pull request merged**
